-- 코드를 입력하세요
WITH CAR_FEE AS (
SELECT DISTINCT A.CAR_TYPE,((A.DAILY_FEE - (A.DAILY_FEE * B.DISCOUNT_RATE)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상'
)

SELECT A.CAR_ID, A.CAR_TYPE, F.FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_FEE F
ON A.CAR_TYPE = F.CAR_TYPE
JOIN (
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE < '2022-11-01'
) B
ON A.CAR_ID = B.CAR_ID
ORDER BY F.FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;