select flavor 
from (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM
FROM
(SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
FROM FIRST_HALF 
UNION ALL
SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
FROM JULY) A
GROUP BY FLAVOR 
order by sum desc) result
where rownum <= 3



