-- 코드를 작성해주세요
# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE EXISTS (SELECT 1 
#               FROM SKILLCODES 
#               WHERE NAME IN ('Python', 'C#') 
#               AND DEVELOPERS.SKILL_CODE & SKILLCODES.CODE = SKILLCODES.CODE)
# ORDER BY ID;


SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID;