-- 코드를 입력하세요
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-10-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
) AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;

