-- 코드를 입력하세요
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, 
(SELECT PRODUCT_NAME 
 FROM FOOD_PRODUCT 
 WHERE CATEGORY = A.CATEGORY 
 AND PRICE = MAX(A.PRICE) LIMIT 1
) AS PRODUCT_NAME
FROM FOOD_PRODUCT A
GROUP BY CATEGORY
HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
